enyo.depends(
    "/socket.io/socket.io.js",
    "api.js",
    "../../Language.js",
    "../../forumdatabase.js",
    "../../init.js",
    "../../style.css",
    "../../lib/onyx",
    "../../kinds",
    "../../lib/extra/jsonp"
);