enyo.depends(
	"/socket.io/socket.io.js",
	"api.js",
	"forumdatabase.js",
	"forumMenu.js",
	"forumView.js",
	"MenuItem.js",
	"MenuItemWithOverlay",
	"settingsView.js",
	"usersView.js",
	"repliesView.js",
	"kinds/Forum.App.js"
);
